/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUIs;


import ReportsGenerators.Report_bill;
import Data.Data_Bill;
import Data.Data_Detail_Bill;
import Data.Data_Products;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Simon Felipe Rua Vargas
 */
public class GUI_Shopping extends javax.swing.JFrame 
{
   private final Data_Products d_prodshop;
   private final Data_Detail_Bill  d_detbill;
   private String cod_bill = "";
    
    /**
     * Creates new form GUI_Shopping
     * @param ID_seller
     * @param ID_client
     * @param code_bill
     */
    public GUI_Shopping(String ID_seller , String ID_client , String code_bill) 
    {
        d_prodshop = new Data_Products();
        d_detbill = new Data_Detail_Bill();
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/images/place order.png")).getImage());
        txtSeller.setText(ID_seller);
        txtClient.setText(ID_client); 
        txt_ShoppingCode.setText(code_bill);
        btn_PickAndPay.setEnabled(false);
    }
    
    public GUI_Shopping(String code_bill)   
    {
        d_prodshop = new Data_Products();
        d_detbill = new Data_Detail_Bill();
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/images/place order.png")).getImage());
        txtSeller.setVisible(false);
        lbl_IDseller.setVisible(false);
        txtClient.setVisible(false);
        lbl_IDclient.setVisible(false);
        txt_ShoppingCode.setText(code_bill);
        btn_PickAndPay.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableDetailBill = new javax.swing.JTable();
        btn_AddShopping = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableproducts = new javax.swing.JTable();
        txt_Product = new javax.swing.JTextField();
        txt_Value = new javax.swing.JTextField();
        txt_RQuantity = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_TotalProducts = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_Payabale = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSeller = new javax.swing.JTextField();
        lbl_IDclient = new javax.swing.JLabel();
        lbl_IDseller = new javax.swing.JLabel();
        txtClient = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_AQuantity = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_IDproduct = new javax.swing.JTextField();
        btn_PickAndPay = new javax.swing.JButton();
        txtPayment = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_ShoppingCode = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtReturn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Btn_SearchAllShopping = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1237, 760));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setMinimumSize(new java.awt.Dimension(1500, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(1500, 760));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableDetailBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product code", "Product", "Requested quantity", "Value"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableDetailBill.setGridColor(new java.awt.Color(255, 255, 255));
        TableDetailBill.setSelectionBackground(new java.awt.Color(102, 255, 51));
        TableDetailBill.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(TableDetailBill);
        TableDetailBill.getAccessibleContext().setAccessibleDescription("");

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 560, 240));

        btn_AddShopping.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_shopping.png"))); // NOI18N
        btn_AddShopping.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_AddShopping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddShoppingActionPerformed(evt);
            }
        });
        jPanel1.add(btn_AddShopping, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 270, 90, 80));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 1420, 10));

        tableproducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Type", "Mark", "Quantity", "Value"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableproducts.setGridColor(new java.awt.Color(255, 255, 255));
        tableproducts.setSelectionBackground(new java.awt.Color(255, 255, 153));
        tableproducts.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tableproducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableproductsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableproducts);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 570, 230));

        txt_Product.setEditable(false);
        txt_Product.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_Product, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 170, 110, -1));

        txt_Value.setEditable(false);
        txt_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_Value, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 200, 110, -1));

        txt_RQuantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_RQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_RQuantityActionPerformed(evt);
            }
        });
        jPanel1.add(txt_RQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 230, 110, -1));

        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/searchproduct.png"))); // NOI18N
        btn_search.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        jPanel1.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 270, 90, 80));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Value:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, 40, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Requested Quantity:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 230, 140, 20));

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setBackground(new java.awt.Color(255, 255, 204));
        jLabel5.setFont(new java.awt.Font("Meiryo UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PRODUCTS");
        jLabel5.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 570, 70));

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Meiryo UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Shopping List");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 560, -1));

        txt_TotalProducts.setEditable(false);
        txt_TotalProducts.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_TotalProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 500, 90, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("TOTAL PRODUCTS:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 500, 130, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("RETURN:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 630, 70, 20));

        txt_Payabale.setEditable(false);
        txt_Payabale.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_Payabale, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 530, 90, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Shopping code: ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, 110, 20));

        txtSeller.setEditable(false);
        txtSeller.setBackground(new java.awt.Color(255, 153, 0));
        txtSeller.setForeground(new java.awt.Color(51, 51, 51));
        txtSeller.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSeller.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtSeller, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, 130, 20));

        lbl_IDclient.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_IDclient.setText("ID client:");
        jPanel1.add(lbl_IDclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, 60, 20));

        lbl_IDseller.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_IDseller.setText("ID seller:");
        jPanel1.add(lbl_IDseller, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 60, 20));

        txtClient.setEditable(false);
        txtClient.setBackground(new java.awt.Color(255, 153, 0));
        txtClient.setForeground(new java.awt.Color(51, 51, 51));
        txtClient.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtClient.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, 130, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Aviable Quantity:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, 110, 20));

        txt_AQuantity.setEditable(false);
        txt_AQuantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_AQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, 110, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil.png"))); // NOI18N
        jLabel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 560, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Product:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, 60, 20));

        txt_IDproduct.setEditable(false);
        txt_IDproduct.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_IDproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 130, 110, 30));

        btn_PickAndPay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pick-n-Pay.png"))); // NOI18N
        btn_PickAndPay.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_PickAndPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PickAndPayActionPerformed(evt);
            }
        });
        jPanel1.add(btn_PickAndPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 500, 130, 80));

        txtPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaymentActionPerformed(evt);
            }
        });
        jPanel1.add(txtPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 590, 110, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("PAYABLE:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 530, 70, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("ID Product:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 80, 20));

        txt_ShoppingCode.setEditable(false);
        txt_ShoppingCode.setBackground(new java.awt.Color(0, 255, 0));
        txt_ShoppingCode.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        txt_ShoppingCode.setForeground(new java.awt.Color(51, 51, 51));
        txt_ShoppingCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_ShoppingCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 390, 180, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("PAYMENT:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 590, 70, 20));
        jPanel1.add(txtReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 630, 110, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil.png"))); // NOI18N
        jLabel6.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 200, -1, -1));

        Btn_SearchAllShopping.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        Btn_SearchAllShopping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SearchAllShoppingActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_SearchAllShopping, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 90, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1420, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
       String name_prod = JOptionPane.showInputDialog(null,"type product's name","PLEASE",JOptionPane.INFORMATION_MESSAGE);
        
       if(name_prod != null)
       {
          d_prodshop.connect_DB();
          d_prodshop.search_product(name_prod);
          d_prodshop.disconnect_DB();
          
          if(d_prodshop.ctc)
             put_dataOnFields();
       }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_AddShoppingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddShoppingActionPerformed
            Add_Shopping();      
    }//GEN-LAST:event_btn_AddShoppingActionPerformed

    private void btn_PickAndPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PickAndPayActionPerformed

            if(!txtReturn.getText().isEmpty())
            {
                d_detbill.connect_DB();
                try 
                {
                    Realize_Report();
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(GUI_Shopping.class.getName()).log(Level.SEVERE, null, ex);
                }
                d_detbill.disconnect_DB();
            }
            else
                JOptionPane.showMessageDialog(null ,"The purshase is incomplete"," ERROR ",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btn_PickAndPayActionPerformed

    private void txtPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaymentActionPerformed
            double payab , payme ;
            String st_payab = txt_Payabale.getText() , st_payme = txtPayment.getText();
        
            if(!st_payab.isEmpty() && !st_payme.isEmpty())
            {
                payab = Double.parseDouble(st_payab);
                
                try
                {
                    payme = Double.parseDouble(st_payme);
                    
                    if(payab > payme)                  
                        JOptionPane.showMessageDialog(null,"The money is not enought to pay the purshase","ATENTION",JOptionPane.WARNING_MESSAGE);
                    else 
                    {
                        txtReturn.setText(String.valueOf(payme - payab));
                        btn_PickAndPay.setEnabled(true);
                    }
                }
                catch(NumberFormatException ex)
                {
                    JOptionPane.showMessageDialog(null,"Only type numbers and type them adequately","ATENTION",JOptionPane.ERROR_MESSAGE);
                }               
            }
            else 
                JOptionPane.showMessageDialog(null,"The client hasn't bought anything yet"," ERROR ", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_txtPaymentActionPerformed

    private void tableproductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableproductsMouseClicked
            if(tableproducts.getSelectedRow() != -1)
            {
               txt_IDproduct.setText((String) tableproducts.getValueAt(tableproducts.getSelectedRow(), 0));
               txt_Product.setText((String) tableproducts.getValueAt(tableproducts.getSelectedRow() , 1));
               txt_Value.setText((String) tableproducts.getValueAt(tableproducts.getSelectedRow() , 5));
               txt_AQuantity.setText((String) tableproducts.getValueAt(tableproducts.getSelectedRow() , 4));
            }
    }//GEN-LAST:event_tableproductsMouseClicked

    private void txt_RQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_RQuantityActionPerformed
            Add_Shopping();
    }//GEN-LAST:event_txt_RQuantityActionPerformed

    private void Btn_SearchAllShoppingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SearchAllShoppingActionPerformed
        d_prodshop.connect_DB();
        d_prodshop.investigate_products_shopping(tableproducts);
        d_prodshop.disconnect_DB();
    }//GEN-LAST:event_Btn_SearchAllShoppingActionPerformed

    /**
     * @param args the command line arguments
     */
//  public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUI_Shopping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUI_Shopping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUI_Shopping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUI_Shopping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUI_Shopping().setVisible(true);
//            }
//        });
//    }

    //<editor-fold defaultstate="collapsed" desc="Variables declaration code">   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_SearchAllShopping;
    private javax.swing.JTable TableDetailBill;
    private javax.swing.JButton btn_AddShopping;
    private javax.swing.JButton btn_PickAndPay;
    private javax.swing.JButton btn_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_IDclient;
    private javax.swing.JLabel lbl_IDseller;
    private javax.swing.JTable tableproducts;
    private javax.swing.JTextField txtClient;
    private javax.swing.JTextField txtPayment;
    private javax.swing.JTextField txtReturn;
    private javax.swing.JTextField txtSeller;
    private javax.swing.JTextField txt_AQuantity;
    private javax.swing.JTextField txt_IDproduct;
    private javax.swing.JTextField txt_Payabale;
    private javax.swing.JTextField txt_Product;
    private javax.swing.JTextField txt_RQuantity;
    private javax.swing.JTextField txt_ShoppingCode;
    private javax.swing.JTextField txt_TotalProducts;
    private javax.swing.JTextField txt_Value;
    // End of variables declaration//GEN-END:variables
    // </editor-fold>  
    
    private void put_dataOnFields() 
    {
           txt_AQuantity.setText(d_prodshop.quantity);
           txt_Value.setText(d_prodshop.value);
           txt_Product.setText(d_prodshop.product_name);
           txt_IDproduct.setText(d_prodshop.id_product);
    }

    private void add_detail_shopping(int rq , long value) 
    {
            String cod_prod = txt_IDproduct.getText();
            Data_Bill d_bill = new Data_Bill();
            
            d_bill.connect_DB();
            cod_bill = d_bill.get_code_bill();
            d_bill.disconnect_DB();   
            
            d_detbill.connect_DB();
            d_detbill.insert_detail_bill(cod_bill , cod_prod , rq , rq*value);///////
            d_detbill.disconnect_DB();          
    }

    private void show_detail_shopping()
    {
            d_detbill.connect_DB();
            d_detbill.search_detail_bill(cod_bill , TableDetailBill);
            d_detbill.disconnect_DB(); 
    }

    private void get_totalprod_shopping() 
    {
            int total_prods;
            
            d_detbill.connect_DB();
            total_prods = d_detbill.sum_total_products(cod_bill);
            d_detbill.disconnect_DB();
            
            txt_TotalProducts.setText(String.valueOf(total_prods));
    }
    
    private void get_payable_shopping()
    {
            double total_payable;
            
            d_detbill.connect_DB();
            total_payable = d_detbill.sum_total_payable(cod_bill);
            d_detbill.disconnect_DB();
            
            txt_Payabale.setText(String.valueOf(total_payable));
    }


    private void update_products_qa(String ID_product , int q) 
    {        
            //Update the aviable quantity of the product
            d_prodshop.connect_DB();
            d_prodshop.update_aviable_quantity(ID_product , String.valueOf(q));
            d_prodshop.disconnect_DB();
            
            //Search again in order to put the updated data
            d_prodshop.connect_DB();
            d_prodshop.investigate_products_shopping(tableproducts);
            d_prodshop.disconnect_DB();
    }
    
    private void clean_fields()
    {
            txt_IDproduct.setText("");
            txt_Product.setText("");
            txt_Value.setText("");
            txt_AQuantity.setText("");
            txt_RQuantity.setText("");
    }

    private void Add_Shopping() 
    {
           String rquantity = txt_RQuantity.getText() , aquantity = txt_AQuantity.getText();
           String val = txt_Value.getText();
           int qr = 0  , qa = 0;
           long value = 0; //////
                  
           if(!txt_IDproduct.getText().isEmpty() && !txt_Product.getText().isEmpty() && !txt_Value.getText().isEmpty()
                && !aquantity.isEmpty() && !rquantity.isEmpty())
            {
                try
                {
                    qr = Integer.parseInt(rquantity); 
                    qa = (int) Double.parseDouble(aquantity);
                    value = (long) Double.parseDouble(val);

                    if(qr > qa)
                       JOptionPane.showMessageDialog(null,"The resquested quantity is greater than the aviable quantity",
                       " PAY ATTENTION ",JOptionPane.WARNING_MESSAGE);
                    else 
                    {
                         if(qr != 0)
                         {   
                            add_detail_shopping(qr,value); ////
                            update_products_qa(txt_IDproduct.getText() , qa-qr);
                            show_detail_shopping();
                            get_totalprod_shopping();
                            get_payable_shopping();
                            clean_fields();
                         }
                         else 
                             JOptionPane.showMessageDialog(null,"The resquested quantity can't be 0",
                             " PAY ATTENTION ",JOptionPane.WARNING_MESSAGE);
                    }
                }
                catch(NumberFormatException e)
                {
                     JOptionPane.showMessageDialog(null ,"fill correctly the requested quantity"
                             + "only numbers"," PLEASE ",JOptionPane.ERROR_MESSAGE);
                     System.err.println(e.getMessage());
                }   
            }
            else
                JOptionPane.showMessageDialog(null,"fill all the datas to complete the purchase"," ERROR ", JOptionPane.ERROR_MESSAGE);
    }
   

    private void Realize_Report() throws FileNotFoundException 
    {
        Report_bill Information;
        Information = new Report_bill("C:\\Users\\simon\\Documents\\JasperReports-Designer\\bill_report.jasper",d_detbill.conect);
            
        Information.createParameter(txt_ShoppingCode.getText());
        Information.showReport_ByParameter();
    }
    

}
