/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUIs;


import Data.Data_Products;
import Data.Data_Suppliers;
import DataSupport.Table_StoreData;
import Render.ModificateTableProducts;
import DataSupport.Thread_Counter;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.*;
import javax.swing.table.TableModel;

/**
 *
 * @author Simon Felipe Rua Vargas
 */
public class GUI_Products_Suppliers extends javax.swing.JFrame 
{
   private final Data_Suppliers d_supplier;
   private final Data_Products d_products;
   private String  ID_supplier;
   private String product_name;
   private Table_StoreData dataIDs_suppls , dataNames_prods;
           
    /**
     * Creates new form GUI_Products_Suppliers
     */
    public GUI_Products_Suppliers() 
    {
        d_supplier = new Data_Suppliers();
        d_products = new Data_Products();
        ID_supplier = "" ;
        product_name = "";
        dataIDs_suppls = null;
        dataNames_prods = null;
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/images/list.png")).getImage());
        products_suppliers_counter();
    }

    /**
     * This method is called from within the constructor to initialize the interface.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PppMenuOptions_Supplier = new javax.swing.JPopupMenu();
        MenuItemUpdateSupplier = new javax.swing.JMenuItem();
        MenuItemEliminateSupplier = new javax.swing.JMenuItem();
        PppMenuOptions_Products = new javax.swing.JPopupMenu();
        MenuItemUpdateProduct = new javax.swing.JMenuItem();
        MenuItemEliminateProduct = new javax.swing.JMenuItem();
        jPanel3 = new javax.swing.JPanel();
        TappedPaneData = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnaddnewsupplier = new javax.swing.JButton();
        btn_Newsupplier = new javax.swing.JButton();
        btn_delete_supplier = new javax.swing.JButton();
        btn_search_supplier = new javax.swing.JButton();
        btn_modificate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_supplier = new javax.swing.JTable();
        btn_seeallsupplier = new javax.swing.JButton();
        Pnl_Suppliers = new javax.swing.JPanel();
        txtName_supplier = new javax.swing.JTextField();
        txtPhone_supplier = new javax.swing.JTextField();
        txtCellphone_supplier = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtID_supplier = new javax.swing.JTextField();
        txtFLN_supplier = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSLN_supplier = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_supplier = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_ProductName = new javax.swing.JTextField();
        txt_ProductType = new javax.swing.JTextField();
        txt_ProductMark = new javax.swing.JTextField();
        txt_ProductValue = new javax.swing.JTextField();
        txt_ProductQuantity = new javax.swing.JTextField();
        txt_ProductSupplierID = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btn_addproduct = new javax.swing.JButton();
        btn_searchproduct = new javax.swing.JButton();
        btn_searchallproducts = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableproducts = new javax.swing.JTable();
        btn_UpdateProduct = new javax.swing.JButton();
        btn_ProductDelete = new javax.swing.JButton();
        btn_NewProduct = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        lbl_products = new javax.swing.JLabel();

        MenuItemUpdateSupplier.setText("Upadate supplier");
        MenuItemUpdateSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemUpdateSupplierActionPerformed(evt);
            }
        });
        PppMenuOptions_Supplier.add(MenuItemUpdateSupplier);

        MenuItemEliminateSupplier.setText("Eliminate supplier");
        MenuItemEliminateSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEliminateSupplierActionPerformed(evt);
            }
        });
        PppMenuOptions_Supplier.add(MenuItemEliminateSupplier);

        MenuItemUpdateProduct.setText("Upadate product");
        MenuItemUpdateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemUpdateProductActionPerformed(evt);
            }
        });
        PppMenuOptions_Products.add(MenuItemUpdateProduct);

        MenuItemEliminateProduct.setText("Eliminate product");
        MenuItemEliminateProduct.setToolTipText("");
        MenuItemEliminateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEliminateProductActionPerformed(evt);
            }
        });
        PppMenuOptions_Products.add(MenuItemEliminateProduct);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form for Products and Suppliers");
        setMinimumSize(new java.awt.Dimension(970, 741));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TappedPaneData.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.darkGray, 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnaddnewsupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add_person.png"))); // NOI18N
        btnaddnewsupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnaddnewsupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnaddnewsupplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnaddnewsupplierMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnaddnewsupplierMousePressed(evt);
            }
        });
        btnaddnewsupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddnewsupplierActionPerformed(evt);
            }
        });
        jPanel1.add(btnaddnewsupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 80, 80));

        btn_Newsupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new_file.png"))); // NOI18N
        btn_Newsupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Newsupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_NewsupplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_NewsupplierMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_NewsupplierMousePressed(evt);
            }
        });
        btn_Newsupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NewsupplierActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Newsupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 80, 80));

        btn_delete_supplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btn_delete_supplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_delete_supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_delete_supplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_delete_supplierMouseExited(evt);
            }
        });
        btn_delete_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_supplierActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 80, 80));

        btn_search_supplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btn_search_supplier.setBorder(null);
        btn_search_supplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_search_supplier.setInheritsPopupMenu(true);
        btn_search_supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_search_supplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_search_supplierMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_search_supplierMousePressed(evt);
            }
        });
        btn_search_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search_supplierActionPerformed(evt);
            }
        });
        jPanel1.add(btn_search_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 80, 80));

        btn_modificate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        btn_modificate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_modificate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_modificateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_modificateMouseExited(evt);
            }
        });
        btn_modificate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_modificate, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 80, 80));

        Table_supplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name(s)", "First Last Name", "Second Last Name", "Phone", "Cellphone"
            }
        ));
        Table_supplier.setComponentPopupMenu(PppMenuOptions_Supplier);
        Table_supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_supplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_supplier);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 810, 260));

        btn_seeallsupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_all_3.png"))); // NOI18N
        btn_seeallsupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_seeallsupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seeallsupplierActionPerformed(evt);
            }
        });
        jPanel1.add(btn_seeallsupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 400, 100, 100));

        Pnl_Suppliers.setBackground(new java.awt.Color(51, 51, 51));
        Pnl_Suppliers.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATA OF THE SUPPLIER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Copperplate Gothic Bold", 0, 14), new java.awt.Color(255, 102, 0))); // NOI18N
        Pnl_Suppliers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtName_supplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtName_supplierKeyTyped(evt);
            }
        });
        Pnl_Suppliers.add(txtName_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 160, 30));

        txtPhone_supplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhone_supplierKeyTyped(evt);
            }
        });
        Pnl_Suppliers.add(txtPhone_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 160, 30));

        txtCellphone_supplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCellphone_supplierKeyTyped(evt);
            }
        });
        Pnl_Suppliers.add(txtCellphone_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 160, 30));
        Pnl_Suppliers.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));
        Pnl_Suppliers.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        txtID_supplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtID_supplierKeyTyped(evt);
            }
        });
        Pnl_Suppliers.add(txtID_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 160, 30));

        txtFLN_supplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFLN_supplierKeyTyped(evt);
            }
        });
        Pnl_Suppliers.add(txtFLN_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 160, 30));
        Pnl_Suppliers.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        txtSLN_supplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSLN_supplierKeyTyped(evt);
            }
        });
        Pnl_Suppliers.add(txtSLN_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 160, 30));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("ID:");
        Pnl_Suppliers.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 30, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Name(s):");
        Pnl_Suppliers.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 60, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("First last name:");
        Pnl_Suppliers.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 110, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Second last name:");
        Pnl_Suppliers.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 130, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText(" Phone:");
        Pnl_Suppliers.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 60, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Cellphone:");
        Pnl_Suppliers.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 80, 30));

        jPanel1.add(Pnl_Suppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 380, 280));

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("number of suppliers:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 180, 20));

        lbl_supplier.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        lbl_supplier.setForeground(new java.awt.Color(255, 102, 0));
        lbl_supplier.setText(".......");
        jPanel1.add(lbl_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 270, 40, 20));

        TappedPaneData.addTab("Personal data supplier", jPanel1);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Control your products here Mr(s)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calisto MT", 0, 18), new java.awt.Color(255, 102, 0))); // NOI18N
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_ProductName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ProductNameKeyTyped(evt);
            }
        });
        jPanel2.add(txt_ProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 120, 30));

        txt_ProductType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ProductTypeKeyTyped(evt);
            }
        });
        jPanel2.add(txt_ProductType, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 120, 30));

        txt_ProductMark.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ProductMarkKeyTyped(evt);
            }
        });
        jPanel2.add(txt_ProductMark, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 120, 30));

        txt_ProductValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ProductValueKeyTyped(evt);
            }
        });
        jPanel2.add(txt_ProductValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 150, 30));

        txt_ProductQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ProductQuantityKeyTyped(evt);
            }
        });
        jPanel2.add(txt_ProductQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 150, 30));

        txt_ProductSupplierID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ProductSupplierIDKeyTyped(evt);
            }
        });
        jPanel2.add(txt_ProductSupplierID, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 150, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Type:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 40, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Name:");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 40, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Mark:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 40, 20));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Value:");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 40, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Quantity:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 60, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Supplier ID:");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 80, -1));

        btn_addproduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_product.png"))); // NOI18N
        btn_addproduct.setBorder(null);
        btn_addproduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_addproduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_addproductMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_addproductMouseExited(evt);
            }
        });
        btn_addproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addproductActionPerformed(evt);
            }
        });
        jPanel2.add(btn_addproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 80, 80));

        btn_searchproduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btn_searchproduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_searchproduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_searchproductMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_searchproductMouseExited(evt);
            }
        });
        btn_searchproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchproductActionPerformed(evt);
            }
        });
        jPanel2.add(btn_searchproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 80, 80));

        btn_searchallproducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_all_5.png"))); // NOI18N
        btn_searchallproducts.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btn_searchallproducts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_searchallproducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchallproductsActionPerformed(evt);
            }
        });
        jPanel2.add(btn_searchallproducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 110, 140));

        tableproducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Type", "Mark", "Quantity", "Value", "Supplier ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableproducts.setComponentPopupMenu(PppMenuOptions_Products);
        tableproducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableproductsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableproducts);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 600, 290));

        btn_UpdateProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        btn_UpdateProduct.setBorder(null);
        btn_UpdateProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_UpdateProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_UpdateProductMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_UpdateProductMouseExited(evt);
            }
        });
        btn_UpdateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateProductActionPerformed(evt);
            }
        });
        jPanel2.add(btn_UpdateProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 80, 80));

        btn_ProductDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_product.png"))); // NOI18N
        btn_ProductDelete.setBorder(null);
        btn_ProductDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ProductDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ProductDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ProductDeleteMouseExited(evt);
            }
        });
        btn_ProductDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProductDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btn_ProductDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 80, 80));

        btn_NewProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new_file.png"))); // NOI18N
        btn_NewProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_NewProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_NewProductMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_NewProductMouseExited(evt);
            }
        });
        btn_NewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NewProductActionPerformed(evt);
            }
        });
        jPanel2.add(btn_NewProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 80, 80));

        jLabel12.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 0));
        jLabel12.setText("NUMBER OF PRODUCTS:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 200, -1));

        lbl_products.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        lbl_products.setForeground(new java.awt.Color(255, 102, 0));
        lbl_products.setText(".....");
        jPanel2.add(lbl_products, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 170, 80, 20));

        TappedPaneData.addTab("Products", jPanel2);

        jPanel3.add(TappedPaneData, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 740));
        TappedPaneData.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_seeallsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seeallsupplierActionPerformed
        d_supplier.connect_DB();
        d_supplier.investigate_supplier(Table_supplier);
        set_TableSupplierIDs_OnArray(Table_supplier.getModel());
        d_supplier.disconnect_DB();
    }//GEN-LAST:event_btn_seeallsupplierActionPerformed

    private void btn_modificateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificateActionPerformed
        if(d_supplier.ctc == true)
        {
            d_supplier.connect_DB();
            d_supplier.update_supplier(txtID_supplier.getText() ,txtName_supplier.getText()
                ,txtFLN_supplier.getText() , txtSLN_supplier.getText(),
                txtPhone_supplier.getText() , txtCellphone_supplier.getText());
            d_supplier.disconnect_DB();
        }
        else
            JOptionPane.showMessageDialog(null,"The supplier has been not found or you forgot 'search supplier'","ERROR",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btn_modificateActionPerformed

    private void btn_search_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search_supplierActionPerformed

        String ID = JOptionPane.showInputDialog(null,"Insert the ID please");
        //RECORDAR EL JOptionPanel showInputDialog retorna en el String , null cuando se le da cancelar y vacio cuando se le da aceptar

        if(ID != null)
        {
            if(ID.isEmpty())
               JOptionPane.showMessageDialog(null,"seriously bro I wont find nobody without the ID","ERROR",JOptionPane.ERROR_MESSAGE);
            else
            {
                d_supplier.connect_DB();
                d_supplier.investigate_supplier_ID(ID);
                d_supplier.disconnect_DB();
            }

            if(d_supplier.ctc == true)
                putting_datas_supplier();
        }
    }//GEN-LAST:event_btn_search_supplierActionPerformed

    private void btn_delete_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_supplierActionPerformed
        String ID = JOptionPane.showInputDialog(null,"Insert the ID please");

        if(ID != null)
        {
            if(ID.isEmpty())
               JOptionPane.showMessageDialog(null,"seriously bro I wont find nobody without the ID","ERROR",JOptionPane.ERROR_MESSAGE);
            else
            {
                d_supplier.connect_DB();
                d_supplier.delete_supplier(ID);
                d_supplier.disconnect_DB();
            }
        }
    }//GEN-LAST:event_btn_delete_supplierActionPerformed

    private void btn_NewsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NewsupplierActionPerformed
        clean_supplier();
    }//GEN-LAST:event_btn_NewsupplierActionPerformed

    private void btnaddnewsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddnewsupplierActionPerformed

        d_supplier.connect_DB();

        d_supplier.insert_supplier(txtID_supplier.getText(),txtName_supplier.getText(),
            txtFLN_supplier.getText(),txtSLN_supplier.getText(),
            txtPhone_supplier.getText(),txtCellphone_supplier.getText());

        d_supplier.disconnect_DB();

        if(d_supplier.ctc == true)
           clean_supplier();
    }//GEN-LAST:event_btnaddnewsupplierActionPerformed

    private void Table_supplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_supplierMouseClicked
         int selected_row = Table_supplier.getSelectedRow();        

        if(selected_row > -1)
           ID_supplier = dataIDs_suppls.getDataOn_ArrayData(selected_row);
            
        System.out.println("ID supplier from MouseClicked event: "+ID_supplier);
         
           //REMEBMER: you have to join the table with the popupmenu in properties of the table, componentpopupmenu and select 
           //the popupmenu that you will use
           if(evt.isPopupTrigger())
            {
               System.err.println("Right click");
               PppMenuOptions_Supplier.setLocation(evt.getX()+100 , evt.getY()+540);
               PppMenuOptions_Supplier.setVisible(true); 
            }
    }//GEN-LAST:event_Table_supplierMouseClicked

    private void MenuItemUpdateSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemUpdateSupplierActionPerformed

        TableModel table = Table_supplier.getModel();
        
        System.err.println("menu 1 supplier");
        System.out.println("ID_supplier outdated: "+ID_supplier);
        
        if(Table_supplier.getSelectedRow() != -1)
        {
            System.out.println("ID supplier table updated: "+ String.valueOf(table.getValueAt(Table_supplier.getSelectedRow() , 0)));
            d_supplier.setId(ID_supplier);
            update_supplier();  //validar update
        }
          
    }//GEN-LAST:event_MenuItemUpdateSupplierActionPerformed

    private void MenuItemEliminateSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEliminateSupplierActionPerformed
        System.err.println("menu 2");
        TableModel table = Table_supplier.getModel();
        
        if(Table_supplier.getSelectedRow() != -1)
            eliminate_supplier(String.valueOf(table.getValueAt(Table_supplier.getSelectedRow() , 0)));
    }//GEN-LAST:event_MenuItemEliminateSupplierActionPerformed

    private void MenuItemUpdateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemUpdateProductActionPerformed
          TableModel table = tableproducts.getModel();
        
          System.err.println("menu 1");
          System.out.println("product name outdated: "+product_name);       
          System.out.println("product name updated: "+ String.valueOf(table.getValueAt(tableproducts.getSelectedRow() , 1)));
          
          if(tableproducts.getSelectedRow() != -1)
          {
             System.err.println(product_name);
             d_products.setproduct_name(product_name);
             update_product();  //validar update                 
          }
    }//GEN-LAST:event_MenuItemUpdateProductActionPerformed

    private void MenuItemEliminateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEliminateProductActionPerformed
        System.err.println("menu 2");
        TableModel table = tableproducts.getModel();
        
        if(tableproducts.getSelectedRow() != -1)
            eliminate_product(String.valueOf(table.getValueAt(tableproducts.getSelectedRow() , 1)));
    }//GEN-LAST:event_MenuItemEliminateProductActionPerformed

    private void btn_NewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NewProductActionPerformed
        clean_product();
    }//GEN-LAST:event_btn_NewProductActionPerformed

    private void btn_ProductDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProductDeleteActionPerformed
        String Name = JOptionPane.showInputDialog(null , "deep the product please");

        if(Name != null)
        {
            if(Name.isEmpty())
            JOptionPane.showMessageDialog(null,"you must fill dat","ERROR DEEEPING THE DATA",JOptionPane.WARNING_MESSAGE);
            else
            {
                d_products.connect_DB();
                d_products.delete_product(Name);
                d_products.disconnect_DB();
            }
        }
    }//GEN-LAST:event_btn_ProductDeleteActionPerformed

    private void btn_UpdateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateProductActionPerformed

        if(d_products.ctc)  //remember: .trim() omits spaces before and after the word but not between word's letters
        {
            d_products.connect_DB();
            d_products.update_product(txt_ProductName.getText(), quit_spaces(txt_ProductType.getText()),
                quit_spaces(txt_ProductMark.getText()) , txt_ProductValue.getText(),
                txt_ProductQuantity.getText(),txt_ProductSupplierID.getText());
            d_products.disconnect_DB();
        }
        else
        JOptionPane.showMessageDialog(null,"You forgot search the product","ERROR",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btn_UpdateProductActionPerformed

    private void tableproductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableproductsMouseClicked
        int selected_row = tableproducts.getSelectedRow();        
        
        if(selected_row > -1)
        {
           product_name = dataNames_prods.getDataOn_ArrayData(selected_row);
           System.out.println("Product name from MouseClicked event: "+product_name);
        } 

        //REMEBMER: you have to join the table with the popupmenu in properties of the table, componentpopupmenu and select
        //the popupmenu that you will use
        if(evt.isPopupTrigger())
        {
            PppMenuOptions_Products.setLocation(evt.getX()+100 , evt.getY()+540);
            PppMenuOptions_Products.setVisible(true);
        }
    }//GEN-LAST:event_tableproductsMouseClicked

    private void btn_searchallproductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchallproductsActionPerformed
        d_products.connect_DB();
        d_products.investigate_products(tableproducts);
        set_TableProductsNames_OnArray(tableproducts.getModel());
        ReviewQuantity_Products();
        d_products.disconnect_DB();
    }//GEN-LAST:event_btn_searchallproductsActionPerformed

    private void btn_searchproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchproductActionPerformed
        String Name = JOptionPane.showInputDialog(null, "Insert the name of the product");

        if(Name != null)
        {
            d_products.connect_DB();
            d_products.search_product(Name);
            d_products.disconnect_DB();

            if(d_products.ctc)
            {
                System.err.println(d_products.ctc);
                putting_data_product();
            }
        }
    }//GEN-LAST:event_btn_searchproductActionPerformed

    private void btn_addproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addproductActionPerformed
        d_products.connect_DB();
        d_products.insert_products(txt_ProductName.getText() , quit_spaces(txt_ProductType.getText()) ,
            quit_spaces(txt_ProductMark.getText()) , txt_ProductQuantity.getText() ,
            txt_ProductValue.getText() , txt_ProductSupplierID.getText());
        d_products.disconnect_DB();
    }//GEN-LAST:event_btn_addproductActionPerformed

    private void btn_ProductDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ProductDeleteMouseEntered
             Border bordercolored = BorderFactory.createLineBorder(Color.RED , 3);
             btn_ProductDelete.setBorder(bordercolored);
    }//GEN-LAST:event_btn_ProductDeleteMouseEntered

    private void btn_ProductDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ProductDeleteMouseExited
             btn_ProductDelete.setBorder(null);       
    }//GEN-LAST:event_btn_ProductDeleteMouseExited

    private void btn_UpdateProductMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UpdateProductMouseEntered
             Border bordercolored = BorderFactory.createLineBorder(Color.RED , 3);
             btn_UpdateProduct.setBorder(bordercolored);
    }//GEN-LAST:event_btn_UpdateProductMouseEntered

    private void btn_UpdateProductMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UpdateProductMouseExited
            btn_UpdateProduct.setBorder(null);
    }//GEN-LAST:event_btn_UpdateProductMouseExited

    private void btn_searchproductMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchproductMouseEntered
            Color Chartreuse = new Color(102 , 255 , 0);
            Border lineborder = BorderFactory.createLineBorder(Chartreuse , 3);                   
            btn_searchproduct.setBorder(lineborder);
    }//GEN-LAST:event_btn_searchproductMouseEntered

    private void btn_searchproductMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchproductMouseExited
            btn_searchproduct.setBorder(null);
    }//GEN-LAST:event_btn_searchproductMouseExited

    private void btn_NewProductMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_NewProductMouseEntered
            Color Chartreuse = new Color(102 , 255 , 0);
            Border lindeborder = BorderFactory.createLineBorder(Chartreuse , 3);   
            btn_NewProduct.setBorder(lindeborder);
    }//GEN-LAST:event_btn_NewProductMouseEntered

    private void btn_NewProductMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_NewProductMouseExited
            btn_NewProduct.setBorder(null);
    }//GEN-LAST:event_btn_NewProductMouseExited

    private void btn_addproductMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addproductMouseEntered
            Color Chartreuse = new Color(102 , 255 , 0);
            Border lindeborder = BorderFactory.createLineBorder(Chartreuse , 3 , true);   
            btn_addproduct.setBorder(lindeborder);
    }//GEN-LAST:event_btn_addproductMouseEntered

    private void btn_addproductMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addproductMouseExited
            btn_addproduct.setBorder(null);
    }//GEN-LAST:event_btn_addproductMouseExited

    private void btn_modificateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificateMouseEntered
            Border softborder = BorderFactory.createSoftBevelBorder(SoftBevelBorder.RAISED,Color.red,Color.RED,Color.red,Color.lightGray);
            btn_modificate.setBorder(softborder);            
    }//GEN-LAST:event_btn_modificateMouseEntered

    private void btn_modificateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificateMouseExited
            btn_modificate.setBorder(null);
    }//GEN-LAST:event_btn_modificateMouseExited

    private void btn_delete_supplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_delete_supplierMouseEntered
            Border softborder = BorderFactory.createSoftBevelBorder(SoftBevelBorder.RAISED,Color.red,Color.RED,Color.red,Color.lightGray);
            btn_delete_supplier.setBorder(softborder);  
    }//GEN-LAST:event_btn_delete_supplierMouseEntered

    private void btn_delete_supplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_delete_supplierMouseExited
            btn_delete_supplier.setBorder(null);
    }//GEN-LAST:event_btn_delete_supplierMouseExited

    private void btn_search_supplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_search_supplierMouseEntered
            Border bevelborder , etchedborder , compoundborder;
            bevelborder = BorderFactory.createBevelBorder(BevelBorder.RAISED);
            etchedborder = BorderFactory.createEtchedBorder(EtchedBorder.LOWERED);
            compoundborder = BorderFactory.createCompoundBorder(etchedborder , bevelborder);
            btn_search_supplier.setBorder(compoundborder);
    }//GEN-LAST:event_btn_search_supplierMouseEntered

    private void btn_search_supplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_search_supplierMouseExited
            btn_search_supplier.setBorder(null);
    }//GEN-LAST:event_btn_search_supplierMouseExited

    private void btn_search_supplierMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_search_supplierMousePressed
            Border  etchedborder;
            etchedborder = BorderFactory.createEtchedBorder(EtchedBorder.LOWERED);
            btn_search_supplier.setBorder(etchedborder);
    }//GEN-LAST:event_btn_search_supplierMousePressed

    private void btn_NewsupplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_NewsupplierMouseEntered
            Border bevelborder , etchedborder , compoundborder;
            bevelborder = BorderFactory.createBevelBorder(BevelBorder.RAISED);
            etchedborder = BorderFactory.createEtchedBorder(EtchedBorder.LOWERED);
            compoundborder = BorderFactory.createCompoundBorder(etchedborder , bevelborder);
            btn_Newsupplier.setBorder(compoundborder);
    }//GEN-LAST:event_btn_NewsupplierMouseEntered

    private void btn_NewsupplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_NewsupplierMouseExited
            btn_Newsupplier.setBorder(null); 
    }//GEN-LAST:event_btn_NewsupplierMouseExited

    private void btn_NewsupplierMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_NewsupplierMousePressed
           Border  etchedborder;
           etchedborder = BorderFactory.createEtchedBorder(EtchedBorder.LOWERED);
           btn_Newsupplier.setBorder(etchedborder);
    }//GEN-LAST:event_btn_NewsupplierMousePressed

    private void btnaddnewsupplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddnewsupplierMouseEntered
            Border bevelborder , etchedborder , compoundborder;
            bevelborder = BorderFactory.createBevelBorder(BevelBorder.RAISED);
            etchedborder = BorderFactory.createEtchedBorder(EtchedBorder.LOWERED);
            compoundborder = BorderFactory.createCompoundBorder(etchedborder , bevelborder);
            btnaddnewsupplier.setBorder(compoundborder);
    }//GEN-LAST:event_btnaddnewsupplierMouseEntered

    private void btnaddnewsupplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddnewsupplierMouseExited
            btnaddnewsupplier.setBorder(null); 
    }//GEN-LAST:event_btnaddnewsupplierMouseExited

    private void btnaddnewsupplierMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddnewsupplierMousePressed
           Border  etchedborder;
           etchedborder = BorderFactory.createEtchedBorder(EtchedBorder.LOWERED);
           btnaddnewsupplier.setBorder(etchedborder);
    }//GEN-LAST:event_btnaddnewsupplierMousePressed

    private void txt_ProductNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ProductNameKeyTyped
            if(evt.getKeyChar() == KeyEvent.VK_ENTER)
                txt_ProductName.transferFocus();             
    }//GEN-LAST:event_txt_ProductNameKeyTyped

    private void txt_ProductTypeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ProductTypeKeyTyped
            if(evt.getKeyChar() == KeyEvent.VK_ENTER)
                txt_ProductType.transferFocus();   
    }//GEN-LAST:event_txt_ProductTypeKeyTyped

    private void txt_ProductMarkKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ProductMarkKeyTyped
            if(evt.getKeyChar() == KeyEvent.VK_ENTER)
                txt_ProductMark.transferFocus();   
    }//GEN-LAST:event_txt_ProductMarkKeyTyped

    private void txt_ProductValueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ProductValueKeyTyped
            if(evt.getKeyChar() == KeyEvent.VK_ENTER)
                txt_ProductValue.transferFocus(); 
    }//GEN-LAST:event_txt_ProductValueKeyTyped

    private void txt_ProductQuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ProductQuantityKeyTyped
            if(evt.getKeyChar() == KeyEvent.VK_ENTER)
                txt_ProductQuantity.transferFocus(); 
    }//GEN-LAST:event_txt_ProductQuantityKeyTyped

    private void txt_ProductSupplierIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ProductSupplierIDKeyTyped
            if(evt.getKeyChar() == KeyEvent.VK_ENTER)
                txt_ProductName.requestFocus();
    }//GEN-LAST:event_txt_ProductSupplierIDKeyTyped

    private void txtName_supplierKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtName_supplierKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_ENTER)
        txtName_supplier.transferFocus();
    }//GEN-LAST:event_txtName_supplierKeyTyped

    private void txtPhone_supplierKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhone_supplierKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_ENTER)
        txtPhone_supplier.transferFocus();
    }//GEN-LAST:event_txtPhone_supplierKeyTyped

    private void txtCellphone_supplierKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCellphone_supplierKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_ENTER)
        txtID_supplier.requestFocus();
    }//GEN-LAST:event_txtCellphone_supplierKeyTyped

    private void txtID_supplierKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtID_supplierKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_ENTER)
        txtID_supplier.transferFocus();
    }//GEN-LAST:event_txtID_supplierKeyTyped

    private void txtFLN_supplierKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFLN_supplierKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_ENTER)
        txtFLN_supplier.transferFocus();
    }//GEN-LAST:event_txtFLN_supplierKeyTyped

    private void txtSLN_supplierKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSLN_supplierKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_ENTER)
        txtSLN_supplier.transferFocus();
    }//GEN-LAST:event_txtSLN_supplierKeyTyped
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//      //  <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUI_Products_Suppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUI_Products_Suppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUI_Products_Suppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUI_Products_Suppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//       // </editor-fold>
//
//  
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable()
//        {
//            @Override
//            public void run() 
//            {
//                   GUI_Products_Suppliers  G_ps = new GUI_Products_Suppliers();
//                   G_ps.setVisible(true);
//            }
//        });
//    }

    // <editor-fold defaultstate="collapsed" desc="Variables declaration">      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemEliminateProduct;
    private javax.swing.JMenuItem MenuItemEliminateSupplier;
    private javax.swing.JMenuItem MenuItemUpdateProduct;
    private javax.swing.JMenuItem MenuItemUpdateSupplier;
    private javax.swing.JPanel Pnl_Suppliers;
    private javax.swing.JPopupMenu PppMenuOptions_Products;
    private javax.swing.JPopupMenu PppMenuOptions_Supplier;
    private javax.swing.JTable Table_supplier;
    private javax.swing.JTabbedPane TappedPaneData;
    private javax.swing.JButton btn_NewProduct;
    private javax.swing.JButton btn_Newsupplier;
    private javax.swing.JButton btn_ProductDelete;
    private javax.swing.JButton btn_UpdateProduct;
    private javax.swing.JButton btn_addproduct;
    private javax.swing.JButton btn_delete_supplier;
    private javax.swing.JButton btn_modificate;
    private javax.swing.JButton btn_search_supplier;
    private javax.swing.JButton btn_searchallproducts;
    private javax.swing.JButton btn_searchproduct;
    private javax.swing.JButton btn_seeallsupplier;
    private javax.swing.JButton btnaddnewsupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_products;
    private javax.swing.JLabel lbl_supplier;
    private javax.swing.JTable tableproducts;
    private javax.swing.JTextField txtCellphone_supplier;
    private javax.swing.JTextField txtFLN_supplier;
    private javax.swing.JTextField txtID_supplier;
    private javax.swing.JTextField txtName_supplier;
    private javax.swing.JTextField txtPhone_supplier;
    private javax.swing.JTextField txtSLN_supplier;
    private javax.swing.JTextField txt_ProductMark;
    private javax.swing.JTextField txt_ProductName;
    private javax.swing.JTextField txt_ProductQuantity;
    private javax.swing.JTextField txt_ProductSupplierID;
    private javax.swing.JTextField txt_ProductType;
    private javax.swing.JTextField txt_ProductValue;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>

    private void update_supplier() 
    {
        TableModel table = Table_supplier.getModel();
        String id , names , fln  , sln , cellphone ,phone;
        
        id = String.valueOf(table.getValueAt(Table_supplier.getSelectedRow() , 0));
        names = (String) table.getValueAt(Table_supplier.getSelectedRow() , 1);
        fln = (String) table.getValueAt(Table_supplier.getSelectedRow() , 2);
        sln = (String) table.getValueAt(Table_supplier.getSelectedRow() , 3);
        phone = (String) table.getValueAt(Table_supplier.getSelectedRow() , 4);
        cellphone = (String) table.getValueAt(Table_supplier.getSelectedRow() , 5);
        
        d_supplier.connect_DB();
        d_supplier.update_supplier(id , names , fln , sln , phone , cellphone);
        d_supplier.investigate_supplier(Table_supplier);
        set_TableSupplierIDs_OnArray(table);
        d_supplier.disconnect_DB();
    }
    
    private void eliminate_supplier(String ID) 
    {
        short op;
        
        if(ID != null)
        {
            if(ID.isEmpty())
               JOptionPane.showMessageDialog(null,"seriously bro I wont find nobody without the ID","ERROR",JOptionPane.ERROR_MESSAGE);
            else
            {
                d_supplier.connect_DB();
                d_supplier.investigate_supplier_ID(ID);
                
                op = (short) JOptionPane.showConfirmDialog(null,"Are you sure you want to eliminate this supplier ?","CONFIRMATION", JOptionPane.YES_NO_OPTION);   
                   
                   if(op == 0)
                       d_supplier.delete_supplier(ID);
                   
                d_supplier.investigate_supplier(Table_supplier);
                set_TableSupplierIDs_OnArray(Table_supplier.getModel());
                d_supplier.disconnect_DB();             
            }
        }
    }
           
    private void putting_datas_supplier()
    {
         txtID_supplier.setText(d_supplier.id);
         txtName_supplier.setText(d_supplier.names);
         txtFLN_supplier.setText(d_supplier.fln);
         txtSLN_supplier.setText(d_supplier.sln);
         txtPhone_supplier.setText(d_supplier.phone);
         txtCellphone_supplier.setText(d_supplier.cellphone);
    }
    
    private void clean_supplier()
    {
        txtID_supplier.setText("");
        txtName_supplier.setText("");
        txtFLN_supplier.setText("");
        txtSLN_supplier.setText("");
        txtPhone_supplier.setText("");
        txtCellphone_supplier.setText("");
    }
    
    private void update_product()
    {
        TableModel table = tableproducts.getModel();
        String  name , type  , mark , value , quantity , ID_suppl;
        
        name = String.valueOf(table.getValueAt(tableproducts.getSelectedRow() , 1));
        type = (String) table.getValueAt(tableproducts.getSelectedRow() , 2);
        mark = (String) table.getValueAt(tableproducts.getSelectedRow() , 3);
        quantity = String.valueOf(table.getValueAt(tableproducts.getSelectedRow() , 4));
        value = String.valueOf(table.getValueAt(tableproducts.getSelectedRow() , 5));
        ID_suppl = String.valueOf(table.getValueAt(tableproducts.getSelectedRow() , 6));
        
        
        d_products.connect_DB();
        d_products.update_product(name , type , mark , quantity , value , ID_suppl);
        d_products.investigate_products(tableproducts);
        set_TableProductsNames_OnArray(table);
        d_products.disconnect_DB();
    }
    
    
    private void putting_data_product()
    {
         txt_ProductName.setText(d_products.product_name);
         txt_ProductType.setText(d_products.type);
         txt_ProductMark.setText(d_products.mark);
         txt_ProductValue.setText(d_products.value);
         txt_ProductQuantity.setText(d_products.quantity);
         txt_ProductSupplierID.setText(d_products.supplier_ID);
    }
    
    private void clean_product()
    {
         txt_ProductName.setText("");
         txt_ProductType.setText("");
         txt_ProductMark.setText("");
         txt_ProductValue.setText("");
         txt_ProductQuantity.setText("");
         txt_ProductSupplierID.setText("");
    }
    
    private void eliminate_product(String product_name) 
    {
           short op;
           op = (short) JOptionPane.showConfirmDialog(null,"Are you sure you want to eliminate this product ?","CONFIRMATION", JOptionPane.YES_NO_OPTION);              
           
          if(op == 0)
          {
             d_products.connect_DB();
             d_products.delete_product(product_name);             
             d_products.investigate_products(tableproducts);
             set_TableProductsNames_OnArray(tableproducts.getModel());
             d_products.disconnect_DB();  
          }
    }
    
    private String quit_spaces(String word)
    {
           String newword = "";
           short i;
           
           for(i=0; i < word.length() ; i++)
           {
               if(word.charAt(i) != ' ')
                  newword += String.valueOf(word.charAt(i));           
           }
           
           return newword;       
    }   
    
  
    private void ReviewQuantity_Products() 
    {
            tableproducts.getColumnModel().getColumn(4).setCellRenderer(new ModificateTableProducts());
            tableproducts.setSelectionBackground(tableproducts.getSelectionBackground());
            tableproducts.setSelectionForeground(tableproducts.getSelectionForeground());
    }

    private void products_suppliers_counter() 
    {
            Thread_Counter thrd_prods,thrd_supps;
            
            thrd_prods = new Thread_Counter("c_prods",lbl_products);
            thrd_supps = new Thread_Counter("c_supps",lbl_supplier);
            
            thrd_prods.start();
            thrd_supps.start();
    }
    
    private void set_TableSupplierIDs_OnArray(TableModel table)
    {
              dataIDs_suppls = new Table_StoreData(table,(short) 0);
              dataIDs_suppls.setDataOn_ArrayData();
    }
    
    private void set_TableProductsNames_OnArray(TableModel table)
    {
              dataNames_prods= new Table_StoreData(table,(short) 1);
              dataNames_prods.setDataOn_ArrayData();
    }
}

