/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

import Data.DataBase_Connection;
import ReportsGenerators.Report_bestseller;
import de.javasoft.plaf.synthetica.SyntheticaBlackEyeLookAndFeel;
import java.io.FileNotFoundException;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
/**
 *
 * @author simon
 */
public class GUI_DateSales extends javax.swing.JFrame 
{
       DataBase_Connection db;
    /**
     * Creates new form GUI_DateSales
     */
    public GUI_DateSales() 
    {
        db = new DataBase_Connection();
        setIconImage(new ImageIcon(getClass().getResource("/images/NumberOne.png")).getImage());
        setLocation(500, 200);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        DateChooser_SecondDate = new com.toedter.calendar.JDateChooser();
        DateChooser_FirstDate = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnGenerateReport = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        DateChooser_SecondDate.setAutoscrolls(true);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setText("SET THE DATES IN ORDER TO GENERATE REPORT   ");

        jLabel2.setText("First date:");

        jLabel3.setText("Second date:");

        BtnGenerateReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ReportBestSeller.png"))); // NOI18N
        BtnGenerateReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnGenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGenerateReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DateChooser_SecondDate, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DateChooser_FirstDate, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(53, 53, 53))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(BtnGenerateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DateChooser_FirstDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DateChooser_SecondDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnGenerateReport, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGenerateReportActionPerformed
        if(DateChooser_FirstDate.getDate() == null || DateChooser_SecondDate.getDate() == null)
           JOptionPane.showMessageDialog(null,"Please fill all the fields","INPUT ERROR",JOptionPane.WARNING_MESSAGE);
        else
        {
             if(validateDates(DateChooser_FirstDate.getDate(),DateChooser_SecondDate.getDate()))
                  try {
                     generateReport();
                  } catch (FileNotFoundException ex){
                    Logger.getLogger(GUI_DateSales.class.getName()).log(Level.SEVERE, null, ex);
                  }
             else
                 JOptionPane.showMessageDialog(null,"The dates was not filled properly","INPUT ERROR" ,JOptionPane.ERROR_MESSAGE);
        }            
    }//GEN-LAST:event_BtnGenerateReportActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /*the look and feel is SyntheticaStandardLookAndFeel*/
//       try 
//      {
//         UIManager.setLookAndFeel(new SyntheticaBlackEyeLookAndFeel());
//      } 
//      catch (Exception e) 
//      {
//         e.printStackTrace();
//      }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                new GUI_DateSales().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGenerateReport;
    private com.toedter.calendar.JDateChooser DateChooser_FirstDate;
    private com.toedter.calendar.JDateChooser DateChooser_SecondDate;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    private boolean validateDates(Date FirstDate , Date SecondDate)
    {
            Calendar Cfirst , Csecond;
            Cfirst = Calendar.getInstance();
            Csecond = Calendar.getInstance();
            
            Cfirst.setTime(FirstDate);
            Csecond.setTime(SecondDate);
            
            if(Cfirst.get(Calendar.MONTH) > Csecond.get(Calendar.MONTH) || 
               Cfirst.get(Calendar.YEAR)!= Csecond.get(Calendar.YEAR))
               return false;
            else
            {
                 return (Cfirst.get(Calendar.MONTH) == Csecond.get(Calendar.MONTH) &&
                         Cfirst.get(Calendar.DAY_OF_MONTH) <= Csecond.get(Calendar.DAY_OF_MONTH));
            }
                   
    }

    private void generateReport() throws FileNotFoundException 
    {
            Report_bestseller reportInstance;
            
            db.connect_DB();
            System.out.println("-----Report generation has been successful----");
            reportInstance = new Report_bestseller("src\\Reports\\Report_sales.jasper",db.conect);
            reportInstance.createParameter(getKeysForParameters() , getDatasForParameters());
            reportInstance.showReport_ByParameter();
            db.disconnect_DB();
    }

    private String[] getKeysForParameters() 
    {
            String[] parameterskeys = {"FirstDate","SecondDate"};
            return parameterskeys;
    }
    
    private Date[] getDatasForParameters()
    {
           Date[] parametersdatas = {DateChooser_FirstDate.getDate() , DateChooser_SecondDate.getDate()};
           return parametersdatas;
    }
}
