/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUIs;


import Data.DataBase_Connection;
import Data.Data_Bill;
import Data.Data_Sellers;
import ReportsGenerators.Report_bill;
import ReportsGenerators.Report_sellers;
import ReportsGenerators.Report_stadistics;
import de.javasoft.plaf.synthetica.SyntheticaBlackEyeLookAndFeel;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import static org.jfree.util.Log.info;


/**
 *
 * @author Simon Felipe Rua Vargas
 */
public class GUI_Main extends javax.swing.JFrame {

    /**
     * Creates new form GUI_main
     */
    public GUI_Main()
    {   
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/images/dollar.png")).getImage());
        setLocationRelativeTo(null);      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        MainLabel = new javax.swing.JLabel();
        Main_menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItem_ProductsSuppliers = new javax.swing.JMenuItem();
        MenuItem_Sellers = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MenuItem_ClientsAndPurchases = new javax.swing.JMenuItem();
        MenuItem_PlaceOrder = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        MenuItem_SellersReports = new javax.swing.JMenuItem();
        MenuItem_BillReports = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        MenuItem_MostBoughtProducts = new javax.swing.JMenuItem();
        MenuItem_StadisticProductType = new javax.swing.JMenuItem();
        MenuItem_BestSeller = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(829, 579));
        setResizable(false);

        MainLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sales.jpg"))); // NOI18N
        getContentPane().add(MainLabel, java.awt.BorderLayout.PAGE_START);

        jMenu1.setText("FORMS");
        jMenu1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N

        MenuItem_ProductsSuppliers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/list.png"))); // NOI18N
        MenuItem_ProductsSuppliers.setText("Products and suppliers");
        MenuItem_ProductsSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_ProductsSuppliersActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItem_ProductsSuppliers);

        MenuItem_Sellers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sellers.png"))); // NOI18N
        MenuItem_Sellers.setText("Sellers");
        MenuItem_Sellers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_SellersActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItem_Sellers);

        Main_menuBar.add(jMenu1);

        jMenu3.setText("SHOPPING");
        jMenu3.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N

        MenuItem_ClientsAndPurchases.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clients.png"))); // NOI18N
        MenuItem_ClientsAndPurchases.setText("Clients and purchases");
        MenuItem_ClientsAndPurchases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_ClientsAndPurchasesActionPerformed(evt);
            }
        });
        jMenu3.add(MenuItem_ClientsAndPurchases);

        MenuItem_PlaceOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/place order.png"))); // NOI18N
        MenuItem_PlaceOrder.setText("Place order");
        MenuItem_PlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_PlaceOrderActionPerformed(evt);
            }
        });
        jMenu3.add(MenuItem_PlaceOrder);

        Main_menuBar.add(jMenu3);

        jMenu5.setText("reports");
        jMenu5.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 15)); // NOI18N

        MenuItem_SellersReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report_sellers.png"))); // NOI18N
        MenuItem_SellersReports.setText("Sellers Reports");
        MenuItem_SellersReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_SellersReportsActionPerformed(evt);
            }
        });
        jMenu5.add(MenuItem_SellersReports);

        MenuItem_BillReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report_bills.png"))); // NOI18N
        MenuItem_BillReports.setText("Bill Reports");
        MenuItem_BillReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_BillReportsActionPerformed(evt);
            }
        });
        jMenu5.add(MenuItem_BillReports);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stadistics.png"))); // NOI18N
        jMenu6.setText("Statistical Reports");

        MenuItem_MostBoughtProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pie_chart.png"))); // NOI18N
        MenuItem_MostBoughtProducts.setText("The 7 products most bought ");
        MenuItem_MostBoughtProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_MostBoughtProductsActionPerformed(evt);
            }
        });
        jMenu6.add(MenuItem_MostBoughtProducts);

        MenuItem_StadisticProductType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chart.png"))); // NOI18N
        MenuItem_StadisticProductType.setText("Products statistic by type");
        MenuItem_StadisticProductType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_StadisticProductTypeActionPerformed(evt);
            }
        });
        jMenu6.add(MenuItem_StadisticProductType);

        MenuItem_BestSeller.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NumberOne.png"))); // NOI18N
        MenuItem_BestSeller.setText("Best salesperson");
        MenuItem_BestSeller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_BestSellerActionPerformed(evt);
            }
        });
        jMenu6.add(MenuItem_BestSeller);

        jMenu5.add(jMenu6);

        Main_menuBar.add(jMenu5);

        setJMenuBar(Main_menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItem_ProductsSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_ProductsSuppliersActionPerformed
                 new GUI_Products_Suppliers().setVisible(true);
    }//GEN-LAST:event_MenuItem_ProductsSuppliersActionPerformed

    private void MenuItem_SellersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_SellersActionPerformed
                GUI_Sellers g_s =  new GUI_Sellers();
                g_s.setVisible(true);
                g_s.setLocationRelativeTo(null);
    }//GEN-LAST:event_MenuItem_SellersActionPerformed

    private void MenuItem_ClientsAndPurchasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_ClientsAndPurchasesActionPerformed
                 new GUI_Clients().setVisible(true);
    }//GEN-LAST:event_MenuItem_ClientsAndPurchasesActionPerformed

    private void MenuItem_PlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_PlaceOrderActionPerformed
        String code_bill;
        Data_Bill d_bill = new Data_Bill();

        d_bill.connect_DB();
        d_bill.insert_order();
        code_bill = d_bill.get_code_bill();
        d_bill.disconnect_DB();

        new GUI_Shopping(code_bill).setVisible(true);
    }//GEN-LAST:event_MenuItem_PlaceOrderActionPerformed

    private void MenuItem_SellersReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_SellersReportsActionPerformed
        Report_sellers info_sellers;
        Data_Sellers d_sellers = new Data_Sellers();   
              
         d_sellers.connect_DB();
         info_sellers = new Report_sellers("src\\Reports\\sellers.jasper",d_sellers.conect);
         info_sellers.showReport();
         d_sellers.disconnect_DB();
    }//GEN-LAST:event_MenuItem_SellersReportsActionPerformed

    private void MenuItem_BillReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_BillReportsActionPerformed
            String code_bill = JOptionPane.showInputDialog("Insert the ID of the bill, please");
            Report_bill info_bills;
            Data_Bill d_bill = new Data_Bill();
            
            if(code_bill != null)
            {
              try 
              {
                 Integer.parseInt(code_bill);
                 d_bill.connect_DB();
                 info_bills = new Report_bill("src\\Reports\\bill_report.jasper",d_bill.conect);
                 info_bills.createParameter(code_bill);
                 info_bills.showReport_ByParameter();
                 d_bill.disconnect_DB();
              } catch (FileNotFoundException | NumberFormatException ex) {
                 JOptionPane.showMessageDialog(null,"it's necesary a numeric value","INPUT ERROR" ,JOptionPane.ERROR_MESSAGE);
                 Logger.getLogger(GUI_Main.class.getName()).log(Level.SEVERE, null, ex);
              }
            }
    }//GEN-LAST:event_MenuItem_BillReportsActionPerformed

    private void MenuItem_MostBoughtProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_MostBoughtProductsActionPerformed
            Report_stadistics stadisticInfo_prods;
            DataBase_Connection d_BaseConnection = new DataBase_Connection();
            
            d_BaseConnection.connect_DB();
            stadisticInfo_prods = new Report_stadistics("src\\Reports\\AllProdStatistic_report.jasper",d_BaseConnection.conect);
            stadisticInfo_prods.showReport();
            d_BaseConnection.disconnect_DB();           
    }//GEN-LAST:event_MenuItem_MostBoughtProductsActionPerformed

    private void MenuItem_StadisticProductTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_StadisticProductTypeActionPerformed
            String product_type = JOptionPane.showInputDialog("Insert the product type , please");
            Report_stadistics info_bills;
            Data_Bill d_bill = new Data_Bill();
            
            if(product_type != null)
            {
              try 
              {
                 d_bill.connect_DB();
                 info_bills = new Report_stadistics("src\\Reports\\Products_statistics.jasper",d_bill.conect);
                 info_bills.createParameter(product_type);
                 info_bills.showReport_ByParameter();
                 d_bill.disconnect_DB();
              }
              catch (FileNotFoundException | NumberFormatException ex) 
              {
                 Logger.getLogger(GUI_Main.class.getName()).log(Level.SEVERE, null, ex);
              }
            }
    }//GEN-LAST:event_MenuItem_StadisticProductTypeActionPerformed

    private void MenuItem_BestSellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_BestSellerActionPerformed
            new GUI_DateSales().setVisible(true);
    }//GEN-LAST:event_MenuItem_BestSellerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {               
          //<editor-fold defaultstate="collapsed" desc=" Look and feel modificated">
       /*the look and feel is SyntheticaStandardLookAndFeel*/
      try 
      {
          UIManager.setLookAndFeel(new SyntheticaBlackEyeLookAndFeel());
      } 
      catch (Exception e) 
      {
         e.printStackTrace();
      }
       //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            @Override
            public void run()
            {
                new GUI_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MainLabel;
    private javax.swing.JMenuBar Main_menuBar;
    private javax.swing.JMenuItem MenuItem_BestSeller;
    private javax.swing.JMenuItem MenuItem_BillReports;
    private javax.swing.JMenuItem MenuItem_ClientsAndPurchases;
    private javax.swing.JMenuItem MenuItem_MostBoughtProducts;
    private javax.swing.JMenuItem MenuItem_PlaceOrder;
    private javax.swing.JMenuItem MenuItem_ProductsSuppliers;
    private javax.swing.JMenuItem MenuItem_Sellers;
    private javax.swing.JMenuItem MenuItem_SellersReports;
    private javax.swing.JMenuItem MenuItem_StadisticProductType;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
