/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUIs;


import Data.Data_Sellers;
import DataSupport.Table_StoreData;
import DataSupport.Thread_Counter;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *Remember: for each investigate_sellers() method, I have a set_TableIDs_OnArray(TableModel table) method
 * @author Simon Felipe Rua Vargas
 */
public class GUI_Sellers extends javax.swing.JFrame 
{
   private Data_Sellers d_seller;
   private String ID_seller;
   private Table_StoreData dataIDs;
           
    /**
     * Creates new GUI_Sellers
     */
    public GUI_Sellers() 
    {
        d_seller = new Data_Sellers();
        ID_seller = "";
        dataIDs = null;
        setIconImage(new ImageIcon(getClass().getResource("/images/sellers.png")).getImage());
        initComponents();     
        sellers_Counter();
    }

    
    /**
     * This method is called from within the constructor to initialize the interface.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PppMenuOptions_Sellers = new javax.swing.JPopupMenu();
        MenuUpdateSeller = new javax.swing.JMenu();
        MenuEliminateSeller = new javax.swing.JMenu();
        backgroundPanel_Sellers = new javax.swing.JPanel();
        Pnl_Sellers = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtID_sellers = new javax.swing.JTextField();
        txtnames_sellers = new javax.swing.JTextField();
        txtFLN_sellers = new javax.swing.JTextField();
        txtSLN_sellers = new javax.swing.JTextField();
        txtphone_sellers = new javax.swing.JTextField();
        txtcellphone_sellers = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btn_seeallsellers = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_sellers = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnaddnewseller = new javax.swing.JButton();
        btn_Newseller = new javax.swing.JButton();
        btn_search_seller = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jSeparator1 = new javax.swing.JSeparator();
        btn_modificateseller = new javax.swing.JButton();
        btn_delete_seller = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbl_sellers = new javax.swing.JLabel();

        PppMenuOptions_Sellers.setToolTipText("");

        MenuUpdateSeller.setText("Update seller");
        MenuUpdateSeller.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuUpdateSellerMousePressed(evt);
            }
        });
        PppMenuOptions_Sellers.add(MenuUpdateSeller);

        MenuEliminateSeller.setText("Delete seller");
        MenuEliminateSeller.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuEliminateSellerMousePressed(evt);
            }
        });
        PppMenuOptions_Sellers.add(MenuEliminateSeller);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sellers Form");
        setMinimumSize(new java.awt.Dimension(1047, 666));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPanel_Sellers.setBackground(new java.awt.Color(51, 51, 51));
        backgroundPanel_Sellers.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, null));
        backgroundPanel_Sellers.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        backgroundPanel_Sellers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backgroundPanel_SellersMouseClicked(evt);
            }
        });
        backgroundPanel_Sellers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pnl_Sellers.setBackground(new java.awt.Color(51, 51, 51));
        Pnl_Sellers.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PERSONAL DATA OF THE SELLER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Copperplate Gothic Bold", 0, 14), new java.awt.Color(255, 102, 0))); // NOI18N
        Pnl_Sellers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Pnl_Sellers.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));
        Pnl_Sellers.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        txtID_sellers.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtID_sellers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtID_sellersKeyTyped(evt);
            }
        });
        Pnl_Sellers.add(txtID_sellers, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 160, 30));

        txtnames_sellers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnames_sellersKeyTyped(evt);
            }
        });
        Pnl_Sellers.add(txtnames_sellers, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 160, 30));

        txtFLN_sellers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFLN_sellersKeyTyped(evt);
            }
        });
        Pnl_Sellers.add(txtFLN_sellers, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 160, 30));

        txtSLN_sellers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSLN_sellersKeyTyped(evt);
            }
        });
        Pnl_Sellers.add(txtSLN_sellers, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 160, 30));

        txtphone_sellers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtphone_sellersKeyTyped(evt);
            }
        });
        Pnl_Sellers.add(txtphone_sellers, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 160, 30));

        txtcellphone_sellers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcellphone_sellersKeyTyped(evt);
            }
        });
        Pnl_Sellers.add(txtcellphone_sellers, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 160, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("ID:");
        Pnl_Sellers.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 30, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Name(s):");
        Pnl_Sellers.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 60, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("First last name:");
        Pnl_Sellers.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 110, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Second last name:");
        Pnl_Sellers.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 130, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText(" Phone:");
        Pnl_Sellers.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 60, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Cellphone:");
        Pnl_Sellers.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 80, 30));

        backgroundPanel_Sellers.add(Pnl_Sellers, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 410, 280));

        btn_seeallsellers.setBackground(new java.awt.Color(51, 51, 51));
        btn_seeallsellers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_all_5.png"))); // NOI18N
        btn_seeallsellers.setToolTipText("");
        btn_seeallsellers.setBorder(null);
        btn_seeallsellers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_seeallsellers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seeallsellersActionPerformed(evt);
            }
        });
        backgroundPanel_Sellers.add(btn_seeallsellers, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 320, 110, 140));

        Table_sellers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name(s)", "First last name", "Second last name", "Phone", "Cellphone"
            }
        ));
        Table_sellers.setComponentPopupMenu(PppMenuOptions_Sellers);
        Table_sellers.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Table_sellers.setDoubleBuffered(true);
        Table_sellers.setGridColor(new java.awt.Color(0, 153, 204));
        Table_sellers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_sellersMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table_sellers);

        backgroundPanel_Sellers.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 780, 330));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ACTIONS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Copperplate Gothic Bold", 0, 14), new java.awt.Color(255, 153, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(204, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnaddnewseller.setBackground(new java.awt.Color(255, 153, 0));
        btnaddnewseller.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add_person.png"))); // NOI18N
        btnaddnewseller.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnaddnewseller.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnaddnewseller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddnewsellerActionPerformed(evt);
            }
        });
        jPanel1.add(btnaddnewseller, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 40, 80, 80));

        btn_Newseller.setBackground(new java.awt.Color(255, 153, 0));
        btn_Newseller.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new_file.png"))); // NOI18N
        btn_Newseller.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Newseller.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Newseller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NewsellerActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Newseller, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 40, 80, 80));

        btn_search_seller.setBackground(new java.awt.Color(255, 153, 0));
        btn_search_seller.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btn_search_seller.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_search_seller.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_search_seller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search_sellerActionPerformed(evt);
            }
        });
        jPanel1.add(btn_search_seller, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 40, 80, 80));
        jPanel1.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 59, -1, -1));
        jPanel1.add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 59, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 58, -1, -1));

        btn_modificateseller.setBackground(new java.awt.Color(255, 102, 0));
        btn_modificateseller.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        btn_modificateseller.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_modificateseller.setContentAreaFilled(false);
        btn_modificateseller.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_modificateseller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificatesellerActionPerformed(evt);
            }
        });
        jPanel1.add(btn_modificateseller, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 80, 80));

        btn_delete_seller.setBackground(new java.awt.Color(255, 153, 0));
        btn_delete_seller.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btn_delete_seller.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_delete_seller.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_delete_seller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_sellerActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete_seller, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 130, 90, 80));

        backgroundPanel_Sellers.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 320, 220));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("SELLERS NUMBER:");
        backgroundPanel_Sellers.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 160, 20));

        lbl_sellers.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        lbl_sellers.setForeground(new java.awt.Color(255, 102, 0));
        lbl_sellers.setText(".....");
        backgroundPanel_Sellers.add(lbl_sellers, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 40, 20));

        getContentPane().add(backgroundPanel_Sellers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1050, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuUpdateSellerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuUpdateSellerMousePressed
        String newID = "";
        TableModel table = Table_sellers.getModel();
        
        System.out.println("MENU 1 SELLERS");
        System.out.println("ID_seller outdated: "+ID_seller);
        
        if(Table_sellers.getSelectedRow() != -1)
        {
            System.out.println("ID seller updated: "+ String.valueOf(table.getValueAt(Table_sellers.getSelectedRow() , 0)));
            d_seller.setId(ID_seller);
            update_Sellers();  //validar update
        }
          
    }//GEN-LAST:event_MenuUpdateSellerMousePressed

    private void MenuEliminateSellerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuEliminateSellerMousePressed
        System.err.println("MENU 2 SELLERS");
        TableModel table = Table_sellers.getModel();
        
        if(Table_sellers.getSelectedRow() != -1)
            eliminate_Sellers(String.valueOf(table.getValueAt(Table_sellers.getSelectedRow() , 0)));
    }//GEN-LAST:event_MenuEliminateSellerMousePressed

    private void backgroundPanel_SellersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundPanel_SellersMouseClicked
        if(PppMenuOptions_Sellers.isVisible())
           PppMenuOptions_Sellers.setVisible(false);
    }//GEN-LAST:event_backgroundPanel_SellersMouseClicked

    private void Table_sellersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_sellersMouseClicked
        int selected_row = Table_sellers.getSelectedRow();        
        
        if(selected_row > -1)
        {
           ID_seller = dataIDs.getDataOn_ArrayData(selected_row);
           System.out.println("ID seller from MouseClicked event: "+ID_seller);
        }
        
       //REMEBMER: you have to join the table with the popupmenu in properties of the table, componentpopupmenu and select
       //the popupmenu that you will use
        if(evt.isPopupTrigger())
        {
            PppMenuOptions_Sellers.setLocation(evt.getX()+100 , evt.getY()+540);
            PppMenuOptions_Sellers.setVisible(true);
        }
    }//GEN-LAST:event_Table_sellersMouseClicked

    private void btn_modificatesellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificatesellerActionPerformed

        if(d_seller.ctc == true)
        {
            d_seller.connect_DB();
            d_seller.update_seller(txtID_sellers.getText() ,txtnames_sellers.getText()
                ,txtFLN_sellers.getText() , txtSLN_sellers.getText(),
                txtphone_sellers.getText() , txtcellphone_sellers.getText());
            d_seller.disconnect_DB();
        }
        else
           JOptionPane.showMessageDialog(null,"The seller has been not found or you forgot 'search seller'","ERROR",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btn_modificatesellerActionPerformed

    private void btn_seeallsellersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seeallsellersActionPerformed
        d_seller.connect_DB();
        d_seller.investigate_sellers(Table_sellers);
        set_TableIDs_OnArray(Table_sellers.getModel());
        d_seller.disconnect_DB();
    }//GEN-LAST:event_btn_seeallsellersActionPerformed

    private void btn_search_sellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search_sellerActionPerformed

        String ID = JOptionPane.showInputDialog(null,"Insert the ID please");
        //RECORDAR EL JOptionPanel showInputDialog retorna en el String , null cuando se le da cancelar y vacio cuando se le da aceptar

        if(ID != null)
        {
            if(ID.isEmpty())
            JOptionPane.showMessageDialog(null,"seriously bro I wont find nobody without the ID","ERROR",JOptionPane.ERROR_MESSAGE);
            else
            {
                d_seller.connect_DB();
                d_seller.investigate_seller_ID(ID);
                d_seller.disconnect_DB();
            }

            if(d_seller.ctc == true)
               putting_Data_Sellers();
        }
    }//GEN-LAST:event_btn_search_sellerActionPerformed

    private void btn_delete_sellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_sellerActionPerformed
        String ID = JOptionPane.showInputDialog(null,"Insert the ID please");
        short op;

        if(ID != null)
        {
            if(ID.isEmpty())
               JOptionPane.showMessageDialog(null,"seriously bro I wont find nobody without the ID","ERROR",JOptionPane.ERROR_MESSAGE);
            else
            {
                d_seller.connect_DB();
                d_seller.investigate_seller_ID(ID);

                if(d_seller.ctc == true)
                {
                    putting_Data_Sellers();
                    op = (short) JOptionPane.showConfirmDialog(null,"Are you sure you want to eliminate this seller ?","CONFIRMATION", JOptionPane.YES_NO_OPTION);

                    if(op == 0)
                       d_seller.delete_seller(ID);
                    else
                       clean_Seller();
                }
                d_seller.disconnect_DB();
            }
        }
    }//GEN-LAST:event_btn_delete_sellerActionPerformed

    private void btn_NewsellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NewsellerActionPerformed
        clean_Seller();
    }//GEN-LAST:event_btn_NewsellerActionPerformed

    private void btnaddnewsellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddnewsellerActionPerformed

        d_seller.connect_DB();

        d_seller.insert_seller(txtID_sellers.getText(),txtnames_sellers.getText(),
            txtFLN_sellers.getText(),txtSLN_sellers.getText(),
            txtphone_sellers.getText(),txtcellphone_sellers.getText());

        d_seller.disconnect_DB();

        if(d_seller.ctc == true)
           clean_Seller();
    }//GEN-LAST:event_btnaddnewsellerActionPerformed

    private void txtID_sellersKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtID_sellersKeyTyped
            if(evt.getKeyChar() == KeyEvent.VK_ENTER)
               txtID_sellers.transferFocus();
    }//GEN-LAST:event_txtID_sellersKeyTyped

    private void txtnames_sellersKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnames_sellersKeyTyped
            if(evt.getKeyChar() == KeyEvent.VK_ENTER)
               txtnames_sellers.transferFocus();
    }//GEN-LAST:event_txtnames_sellersKeyTyped

    private void txtFLN_sellersKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFLN_sellersKeyTyped
            if(evt.getKeyChar() == KeyEvent.VK_ENTER)
               txtFLN_sellers.transferFocus();
    }//GEN-LAST:event_txtFLN_sellersKeyTyped

    private void txtSLN_sellersKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSLN_sellersKeyTyped
            if(evt.getKeyChar() == KeyEvent.VK_ENTER)
               txtSLN_sellers.transferFocus();
    }//GEN-LAST:event_txtSLN_sellersKeyTyped

    private void txtphone_sellersKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphone_sellersKeyTyped
            if(evt.getKeyChar() == KeyEvent.VK_ENTER)
               txtphone_sellers.transferFocus(); 
    }//GEN-LAST:event_txtphone_sellersKeyTyped

    private void txtcellphone_sellersKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcellphone_sellersKeyTyped
            if(evt.getKeyChar() == KeyEvent.VK_ENTER)
               txtID_sellers.requestFocus();
    }//GEN-LAST:event_txtcellphone_sellersKeyTyped
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) 
//    {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUI_Sellers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUI_Sellers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUI_Sellers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUI_Sellers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable()
//        {
//            @Override
//            public void run() 
//            {
//                new GUI_Sellers().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuEliminateSeller;
    private javax.swing.JMenu MenuUpdateSeller;
    private javax.swing.JPanel Pnl_Sellers;
    private javax.swing.JPopupMenu PppMenuOptions_Sellers;
    private javax.swing.JTable Table_sellers;
    private javax.swing.JPanel backgroundPanel_Sellers;
    private javax.swing.JButton btn_Newseller;
    private javax.swing.JButton btn_delete_seller;
    private javax.swing.JButton btn_modificateseller;
    private javax.swing.JButton btn_search_seller;
    private javax.swing.JButton btn_seeallsellers;
    private javax.swing.JButton btnaddnewseller;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_sellers;
    private javax.swing.JTextField txtFLN_sellers;
    private javax.swing.JTextField txtID_sellers;
    private javax.swing.JTextField txtSLN_sellers;
    private javax.swing.JTextField txtcellphone_sellers;
    private javax.swing.JTextField txtnames_sellers;
    private javax.swing.JTextField txtphone_sellers;
    // End of variables declaration//GEN-END:variables
    
    private void update_Sellers()
    {
        TableModel table = Table_sellers.getModel();
        String id , names , fln  , sln , cellphone ,phone;
        
        id = String.valueOf(table.getValueAt(Table_sellers.getSelectedRow() , 0));
        names = (String) table.getValueAt(Table_sellers.getSelectedRow() , 1);
        fln = (String) table.getValueAt(Table_sellers.getSelectedRow() , 2);
        sln = (String) table.getValueAt(Table_sellers.getSelectedRow() , 3);
        cellphone = (String) table.getValueAt(Table_sellers.getSelectedRow() , 4);
        phone = (String) table.getValueAt(Table_sellers.getSelectedRow() , 5);
        
        d_seller.connect_DB();
        d_seller.update_seller(id , names , fln , sln , cellphone , phone);
        d_seller.investigate_sellers(Table_sellers);
        set_TableIDs_OnArray(table);//---------------------------------
        d_seller.disconnect_DB();
    }
    
    private void eliminate_Sellers(String ID)
    {
        short op;
        
        if(ID != null)
        {
            if(ID.isEmpty())
               JOptionPane.showMessageDialog(null,"seriously bro I wont find nobody without the ID","ERROR",JOptionPane.ERROR_MESSAGE);
            else
            {
                d_seller.connect_DB();
                d_seller.investigate_seller_ID(ID);
                
                   op = (short) JOptionPane.showConfirmDialog(null,"Are you sure you want to eliminate this seller ?","CONFIRMATION", JOptionPane.YES_NO_OPTION);   
                   
                   if(op == 0)
                      d_seller.delete_seller(ID);
                   
                      d_seller.investigate_sellers(Table_sellers);
                      set_TableIDs_OnArray(Table_sellers.getModel());//----------------------                                             
                              
                d_seller.disconnect_DB();             
            }
        }
    }
    
    private void putting_Data_Sellers()
    {
         txtID_sellers.setText(d_seller.id);
         txtnames_sellers.setText(d_seller.names);
         txtFLN_sellers.setText(d_seller.fln);
         txtSLN_sellers.setText(d_seller.sln);
         txtphone_sellers.setText(d_seller.phone);
         txtcellphone_sellers.setText(d_seller.cellphone);
    }
    
    private void clean_Seller()
    {
        txtID_sellers.setText("");
        txtnames_sellers.setText("");
        txtFLN_sellers.setText("");
        txtSLN_sellers.setText("");
        txtphone_sellers.setText("");
        txtcellphone_sellers.setText("");
        
    }  

    private void sellers_Counter() 
    {
             Thread_Counter thrd_seller = new Thread_Counter("c_sellers",lbl_sellers);           
             thrd_seller.start();
    }

    private void set_TableIDs_OnArray(TableModel table)
    {
              dataIDs = new Table_StoreData(table , (short) 0);
              dataIDs.setDataOn_ArrayData();
    }
      
}

